dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
platforms:
  - name: instance
    box: centos/stream8
    memory: 512
    cpus: 1
    instance_raw_config_args:
      - vagrant.plugins = ["vagrant-libvirt"]
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "'vagrant'"
      synced_folder: false
    interfaces:
      - network_name: forwarded_port
        guest: 80
        host: 8080
    provision: no
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        fedmsg_env: stg
verifier:
  name: ansible